In [1]:
%load_ext autoreload
%autoreload 2 

In [2]:
import numpy as np
import tensorflow as tf

import layers_experimental

In [3]:
mock_capsules = np.array([
    [
        [[[1,2,3], [10,20,30]],[[4,5,6], [40,50,60]],[[7,8,9], [70,80,90]]],
        [[[10,11,12], [100,110,120]], [[13,14,15],[130,140,150]], [[16,17,18], [160, 170, 180]]],
    ],
])

mock_capsules

array([[[[[  1,   2,   3],
          [ 10,  20,  30]],

         [[  4,   5,   6],
          [ 40,  50,  60]],

         [[  7,   8,   9],
          [ 70,  80,  90]]],


        [[[ 10,  11,  12],
          [100, 110, 120]],

         [[ 13,  14,  15],
          [130, 140, 150]],

         [[ 16,  17,  18],
          [160, 170, 180]]]]])

In [15]:
tf.reset_default_graph()

inputs = tf.constant(mock_capsules, dtype=tf.float32)
outputs = layers_experimental.convCaps(inputs, 2, 5, 3, 1, 3)

In [16]:
outputs

<tf.Tensor 'convCaps/caps_conv2d/caps_route/outputs:0' shape=(?, 2, 3, 2, 5) dtype=float32>

In [17]:
file_writer = tf.summary.FileWriter('debug_logs', tf.get_default_graph())

In [18]:
init = tf.global_variables_initializer()

with tf.Session() as sess:
    init.run()
    
    o = sess.run(outputs)

In [19]:
o.shape

(1, 2, 3, 2, 5)

In [52]:
sq1_v[0, 0, 0, 0, 0, :, :]

array([[ 0.9945697],
       [-0.9592437],
       [-0.9961259],
       [-0.9988801],
       [-0.9986631]], dtype=float32)

In [63]:
sq1_v[0, 0, 0, 0, 0, :, 0]

array([ 0.9945697, -0.9592437, -0.9961259, -0.9988801, -0.9986631],
      dtype=float32)

In [64]:
np.sqrt(np.sum(np.square(sq1_v[0, 0, 0, 0, 0, :, 0])))

2.212843

In [59]:
sq2_v[0, 0, 0, 0, 0, :, 0]

array([ 0.29499096, -0.10574711, -0.34952062, -0.6509707 , -0.59575164],
      dtype=float32)

In [66]:
np.sqrt(np.sum(np.square(sq2_v[0,0,0,0,0,:,0])))

0.9995247